### ISSUE TITLE
Planning A Hackathon-Learning v. Doing

### ISSUE THREAD

**Issue by laurencjay** [womenwhocodedc/organization#39]
Brainstorming has begun for a women who code hackathon sometime in April of 2016. We have started thinking about our experiences with hackathons/what we might want to see out of a women who code hackathon. 

This is to specifically address the 'learning' v. 'doing' hackathons tracks. I would love any and all feedback on the following:
1. Should the hackathon focus on doing (have people and organizations bring projects to work on and hack at) or learning (having teaching sessions similar to Tech Lady Hackathon)? 
2. Do you think teaching sessions are useful? Would interspersing the day with 'inspiring' talks from women in the tech industry be more interesting/compelling?
3. Do you think that it would be more useful to incorporate the 'learning' aspect of the hackathon by adding one newbie to each project team to learn by doing/observing?
4. How do you feel about giving prizes out for hackathons? What types of alternatives traditional prizes can you think of?

Feel free to provide your feedback on any/all of the topics above. Thanks so much!
-Lauren 

@womenwhocodedc/all

**Comment by emgrasmeder** [comment]
1. I think _doing_ hackathons are way more empowering. Especially if we emphasize the fact that the hardcore coders in the groups aren't superheros, & anyone can get to that point.
2. Teaching will help some and bore others. What if we taught less experienced people how to get involved and let them loose to join teams afterwards. Inspiring talks (like getting Aliya Rahman to talk, for example) would be my personal preference. 
3. Yes
4. In any case we should definitely highlight the teams accomplishments and feature them on Medium and tweet about them. I feel -2 on the [-10,10] scale about encouraging people to compete with each other.

**Comment by kdmcclin** [comment]
I'm with Emma on the doing part.  I do think there's something to be said about a mixed approach too, like the have a small tutorial session earlier in the day and then get to projects idea.  I wonder if there's virtue in having a small selection of projects/ideas already so that people who don't have an idea or don't have a team to join don't have to feel that pressure.  And I know not everyone is, but I'd be willing to complete less work in the end, but talk about it more as I go along so people could see the process. :heavy_plus_sign: on Emma's point #4 too.

**Comment by iamanissa** [comment]
I have never been to a hack a thon. So, from that perspective, I would be intimidated to just jump in and hack. I think splitting groups and having the doers do and the learners learn for the first half and then the newbies join in for the second half on a new project. I don't know if half a session would be long enough to get enough done though. 
If that wouldn't work than I think all doing is better than all teaching. 
I agree with emma on the last two points.

**Comment by Freetown5** [comment]
I'm completely on Emma and Katherine's side on this. I feel like the biggest issue I've had with hackathons has been that they try to focus on both workshops and actual hacking and one, usually hacking, almost always inevitably falls to the wayside. Women Who Code already has plenty of workshops and classes dedicated to introducing newbies to tech. We need at least one event where people are actually able to use the skills they have to do something of substance. Something that they can put in their portfolio or possibly turn into an actual business. We can ease the fears of newer coders by having "what to expect" presentations like the one the Ruby group is doing for the Rails Conf. the week before the event and we can make it clear we're designer and business professional friendly the way other hackathons do in the descriptions and through promotions on slack and at meetings.

**Comment by iamanissa** [comment]
Oh @Freetown5 I think that is a great Idea. To do "what to expect" presentations in each group the week before. I think everyone would love to have something to put in a portfolio.

**Comment by dcwebmaven** [comment]
I love all the ideas I've read so far!  I think the best way to incorporate "newbies" is to have them join an existing team and then the team can figure out what to have them do.  A what to expect the week before would be excellent, as well as having a bunch of projects set up/identified even when you're advertising the event so people can think about what kind of project they might want to work on.  Smaller teams (like 4 or 5 people) seem to work better than huge groups, because then you can divide up responsibilities more or less equally, rather than having a bunch of people standing around waiting for an opportunity to do something.

I agree that everyone can use a portfolio boost and one or two inspiring talks. Since I'm absolutely not up for an all-nighter, I prefer to have the focus be on the projects for the day and then go home at night, so the more hands-on project time we have from the beginning, the better. You didn't mention whether it was a 24-hour type of hackathon or what kind of timeframe is being contemplated.  That would be helpful to know to help figure out what's doable; my vote is for a 9-5 kind of deal, but then you don't get as far on a project.

**Comment by venikunche** [comment]
These are my thoughts as someone who has never been to a hackathon:

As a participant (with development experience):
- I do not like the ones where you pitch an idea and compete. It feels like a popularity contest. The viability of an idea is dependent on potential customers and not on the judge's or other participant's opinions.
- The only ones I considered going to are something like https://codersvscancer.splashthat.com/ where there is a specific goal or challenge. I like knowing that what I worked on has the potential to be useful to someone.

As a mentor:
- I have been wanting to go to a hackathon to help out. Unfortunately, no one clearly states what the expectations are. They just say you don't need to be a pro. I like knowing my responsibilities ahead of time so that I can prepare.
- I suggest we clearly state the roles and responsibilities of mentors.

For participants who are new to coding but have started to learn:
- In general, I agree with more doing with a little bit of learning. You can read and do as many tutorials as one wants. It doesn't mean much unless you actually put it to use.
- I suggest a beginner level project/challenge that they can work on with the help of mentors or have someone lead the group on a specific project.

I also suggest talking to a few members who are new to coding, who just started to learn and those who are experienced and ask them what they expect from a hackathon.

All of these are my opinions. Take them lightly as I have not been to a hackathon before :)

**Comment by tgmiller5** [comment]
Here is my thoughts:
Should the hackathon focus on doing (have people and organizations bring projects to work on and hack at) or learning (having teaching sessions similar to Tech Lady Hackathon)?
Answer: I think it would be greate to focus on doing over learning. As for me, I learn more by doing than anything. 

Do you think teaching sessions are useful? Would interspersing the day with 'inspiring' talks from women in the tech industry be more interesting/compelling?
Teaching sessions are useful. I would not have too many talks as the focus should be on more doing for programming

Do you think that it would be more useful to incorporate the 'learning' aspect of the hackathon by adding one newbie to each project team to learn by doing/observing?
I think it should be broken down into sections such as a beginner section, intermeditate to advanced session. 

How do you feel about giving prizes out for hackathons? What types of alternatives traditional prizes can you think of?

**Comment by pamtaro** [comment]
I like @SuperJones idea of splitting the groups into learners and doers where the learners get to learn for the first half and then get to join the rest of the doers in the 2nd half.

This is actually what DCWW's Women's Hackathon was like in August. The beginners were in a session for the first half of the day learning HTML/CSS and then for the 2nd half of the day they were given a template to work off of so they can practice what they learned and build a website. The template was used by all the beginners, but the doer's had to make something from scratch. At the end of the day, both groups joined together for demoing what they were able to build. The experienced doers were judged and awarded separately from the beginners (since it wouldn't be fair to have them judged against the same criteria).
